### ISSUE TITLE
List of Projects

### ISSUE THREAD

**Issue by mgrover1** [openradar/erad2024#12]
Create a list of projects and short project descriptions for the afternoon session.

- [ ] LROSE wind tools  + PyDDA retrieval over complex terrain #52 
- [ ] #6
- [ ] QPE exercise in the north of Italy (pyrad + Py-ART) #51
- [ ] Creating analysis-ready data with xradar with QVPs (xradar) #53

**Comment by tingyucha** [comment]
LROSE wind tools retrieval over complex terrain

**Comment by jfigui** [comment]
For Pyrad we are planning a QPE exercise in the north of Italy

**Comment by ghiggi** [comment]
To keep track of https://github.com/openradar/erad2024/issues/6 progress and discussions, follow the corresponding issue.

**Comment by mgrover1** [comment]
Once we have #104 and #105 here, I can put together a PR adding in the project page 👍 

That should close some of these PRs... and then we can cut a release which would close #78
