### ISSUE TITLE
ROADMAP to ERAD2024

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2024#3]
This issue just shows the roadmap to ERAD2024. We'll provide a list of dates to keep track of course development:

1. Initial repo setup
    - [x] add collaborators (done, invitations sent out) 
    - [x] update theme/readme #2 
    - [x] enable nightly builds https://github.com/openradar/erad2024/commit/edb12d6b5f604fe911dc533321717f5179b28a51 #4 
    - [x] #42
    - [x] #57 
    - [x] #61
    - [x] #67   
    - [x] #77
    - [ ] tbc
2. Initial working environment ready
    - [x] #8 
    - [x] #9
    - [x] #74
    - [x] #75
    - [ ] tbc
3. Docker image ready
    - [x] #31, #32
    - [ ] tbc
5. All packages available in environment/docker
    - [x] LROSE
    - [x] wradlib, pyart
    - [x] BALTRAD needs a bit of love #39
    - [ ] tbc
7. Presentations ready
    - [ ] tbc
8. Resources ready (data etc.)
    - [x] #12 
9. Notebooks ready
    - [x] #11, #34
    - [x] #45
    - [x] #55
    - [x] #41 
    - [x] #66
    - [x] #65 
    - [ ] tbc
10. Complete workflow ready
    - [ ] tbc

**Comment by mgrover1** [comment]
@kmuehlbauer - can we revisit this issue, and use it to highlight tasks we want to get done during the sprint?
